name: Run All Tests

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'cli/**'
      - 'tests/**'
      - 'requirements.txt'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'cli/**'
      - 'tests/**'
      - 'requirements.txt'
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run all tests
      run: |
        pytest tests/ -v --cov=src --cov=cli
        
    - name: Generate coverage report
      run: |
        pytest --cov=src --cov=cli --cov-report=xml
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
